- id: check-tags
  name: Check tag in a file
  description: "Checks if a required tag with the right attribute(Environment, AssetId) exists in a specific file."
  entry: ./check-tags.sh
  language: script
  always_run: true
  files: \.tfvars$|\.tf$
  exclude: ^(README\.md|main\.tf)$