- id: check-substring
  name: Check substring in a file
  description: "Checks if a required substring exists in a specific file."
  entry: ./check-substring.sh
  language: script
  always_run: true
  files: \.tfvars$|\.tf$
